package com.jhiltunen.finnishparliamentmembers.ui.fragments

import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.databinding.DataBindingUtil
import androidx.fragment.app.Fragment
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.observe
import androidx.recyclerview.widget.GridLayoutManager
import com.jhiltunen.finnishparliamentmembers.R
import com.jhiltunen.finnishparliamentmembers.databinding.FragmentMemberViewDetailsBinding
import com.jhiltunen.finnishparliamentmembers.databinding.FragmentPartiesListBinding
import com.jhiltunen.finnishparliamentmembers.logic.viewmodels.ParliamentMemberDetailsViewModel
import com.jhiltunen.finnishparliamentmembers.logic.viewmodels.PartiesViewModel
import com.jhiltunen.finnishparliamentmembers.ui.adapters.PartiesListAdapter

/**
 * Fragment that displays all parties belonging to Finnish Parliament. .
 * User can select party and then see list of members belonging to that party.
 */
class PartiesFragment : Fragment() {
    private lateinit var binding: FragmentPartiesListBinding
    private lateinit var viewModel: PartiesViewModel
    private lateinit var adapter: PartiesListAdapter

    /**
     * Called when the Fragment is ready to display content to the screen.
     *
     * This function uses DataBindingUtil to inflate R.layout.fragment_member_view_details.
     *
     * It is also responsible for passing the [ParliamentMemberDetailsViewModel] to the
     * [FragmentMemberViewDetailsBinding] generated by DataBinding. This will allow DataBinding
     * to use the [LiveData] on our ViewModel.
     */
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Get a reference to the binding object and inflate the fragment views.
        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_parties_list, container, false)

        // Get a reference to the ViewModel associated with this fragment.
        viewModel = ViewModelProvider(this).get(PartiesViewModel::class.java)
        // To use the View Model with data binding, you have to explicitly
        // give the binding object a reference to it.
        binding.viewModel = viewModel

        // If there is no data on database
        if (viewModel.parties.value == null) {
            // Fetch data from Eduskunta API
            viewModel.fetchDataFromApi()
        }

        // Adapter for recyclerview
        adapter = PartiesListAdapter(requireContext(), viewModel.parties)

        binding.list.adapter = adapter
        binding.list.layoutManager = GridLayoutManager(context, 4)

        // Add an Observer to detect database changes on parties name list
        viewModel.parties.observe(viewLifecycleOwner) {
            Log.d("LISTA", "$it")
            adapter.submitList(it)
        }

        return binding.root
    }
}